language: cpp
dist: trusty
sudo: required
os: linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libace-dev
  - '[[ "$TRAVIS_EVENT_TYPE" = cron ]] && export YARP_CHECKOUT=devel || export YARP_CHECKOUT=master'

install:
  # Clone and build YARP
  - cd
  - git clone --depth=1 --branch=$YARP_CHECKOUT https://github.com/robotology/yarp
  - mkdir -p yarp/build && cd "$_"
  - cmake ..
  - sudo make -j2 install

  # Clone and configure ROBOTICSLAB_KINEMATICS_DYNAMICS
  - cd
  - git clone --branch=fix-104-cmake-exports https://github.com/roboticslab-uc3m/kinematics-dynamics
  - mkdir -p kinematics-dynamics/build && cd "$_"
  - cmake .. -DENABLE_TrajectoryLib:BOOL=OFF -DENABLE_KdlVectorConverterLib:BOOL=OFF -DENABLE_YarpTinyMathLib:BOOL=OFF -DENABLE_BasicCartesianControl:BOOL=OFF -DENABLE_CartesianControlServer:BOOL=OFF -DENABLE_CartesianControlClient:BOOL=OFF -DENABLE_KdlSolver:BOOL=OFF -DENABLE_AsibotSolver:BOOL=OFF -DENABLE_BasicTwoLimbCartesianControl:BOOL=OFF -DENABLE_TwoLimbCartesianControlServer:BOOL=OFF -DENABLE_transCoordsUsingJoints:BOOL=OFF -DENABLE_tests:BOOL=OFF
  - export ROBOTICSLAB_KINEMATICS_DYNAMICS_DIR=$PWD

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ..

script:
  - make
