language: cpp
dist: trusty
sudo: required
os: linux

compiler:
  - gcc
  - clang

before_install:
  #- sudo apt-get -qq update
  - '[[ "$TRAVIS_EVENT_TYPE" = cron ]] && export ROBOTOLOGY_CHECKOUT=devel || export ROBOTOLOGY_CHECKOUT=master'

install:
  # Install color-debug
  - git clone https://github.com/roboticslab-uc3m/color-debug
  - mkdir -p color-debug/build && cd "$_"
  - cmake ..
  - sudo make install
  - cd ../..

  #-- Install YCM
  - git clone --branch="$ROBOTOLOGY_CHECKOUT" https://github.com/robotology/ycm
  - mkdir -p ycm/build && cd "$_"
  - cmake ..
  - make -j$(nproc)
  - sudo make install
  - cd ../..

  # Clone and build YARP
  - git clone --depth=1 --branch=$ROBOTOLOGY_CHECKOUT https://github.com/robotology/yarp
  - mkdir -p yarp/build && cd "$_"
  - cmake .. -DSKIP_ACE=ON
  - make -j$(nproc)
  - sudo make install
  - cd ../..

  # Clone and configure ROBOTICSLAB_KINEMATICS_DYNAMICS
  - git clone https://github.com/roboticslab-uc3m/kinematics-dynamics
  - mkdir -p kinematics-dynamics/build && cd "$_"
  - cmake ..
  - export ROBOTICSLAB_KINEMATICS_DYNAMICS_DIR=$PWD
  - cd ../..

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ..

script:
  - make && sudo make install

after_success:
  - sudo make uninstall
