language: cpp
dist: trusty
sudo: required
os: linux

compiler:
  - gcc
  - clang

before_install:
  #- sudo apt-get -qq update
  - '[[ "$TRAVIS_EVENT_TYPE" = cron ]] && export YARP_CHECKOUT=devel || export YARP_CHECKOUT=master'

install:
  # Clone and build YARP
  - cd
  - git clone --depth=1 --branch=$YARP_CHECKOUT https://github.com/robotology/yarp
  - mkdir -p yarp/build && cd "$_"
  - cmake .. -DSKIP_ACE=ON
  - make -j$(nproc)
  - sudo make install

  # Clone and configure ROBOTICSLAB_KINEMATICS_DYNAMICS
  - cd
  - git clone https://github.com/roboticslab-uc3m/kinematics-dynamics
  - mkdir -p kinematics-dynamics/build && cd "$_"
  - cmake ..

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ..

script:
  - make

after_success:
  - sudo make install
